import { Inter } from 'next/font/google'
import { SpeedInsights } from '@vercel/speed-insights/next';

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Thala For A Reason',
  description: 'Generated by create next app',
  /* 
    icons: {
      icon: [
        {
          url: '/light-icon.png', // path in /public directory
          media: '(prefers-color-scheme: light)',
        },
        {
          url: '/dark-icon.png', // path in /public directory
          media: '(prefers-color-scheme: dark)',
        },
      ],
    }, 
  */
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <SpeedInsights />
      </body>
    </html>
  )
}
